### ISSUE TITLE
[meta] rough prototype

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/nergal#7]
Грубому прототипу - грубый план!
- [x] нарисовать просто цветной треугольник при помощи glium
- [x] запустить на андроиде
- [x] завести хранилище `nergal_assets` для ресурсов
- [x] вынести шейдеры из кода в ресурсы
- [x] добавить текстуру к треугольнику (#13)
- [ ] скелетная анимация (md5) сетки (#4)
- [ ] научиться экспортировать md5 из блендера (#14)
- [ ] экспорт и отображение .obj файлов (#17)
- [x] завести хранилище `nergal_assets_src` для исходников ресурсов
- [ ] взять модель человечка из Зоны Контроля, сделать для него тестовую анимацию
- [ ] прикрепление предметов к костям (#15)
- [ ] система частиц (#5)
- [ ] рисование карты и выбор клетки под курсором
- [ ] камера
- [ ] нахождение пути
- [ ] выделение и перемещение существ по путям
- [ ] нарисовать и внедрить анимацию перемещения
- [ ] очки действия
- [ ] сериализация и загрузка игрового состояния
- [ ] враги без ИИ + базовые атаки (без математики) + анимации атаки и смерти
- [ ] простые очки жизни (смерть после пары ударов)
- [ ] примитивный ИИ (подходит на дальность атаки и бьет)
- [ ] базовая математика урона/брони/уклонения
- [ ] базовые характеристики и навыки персонажей
- [ ] ослабление персонажей при получении урона
- [ ] контратаки
- [ ] реакционные атаки
- [ ] рисование текста (#8)
- [ ] базовый xcom-подобный интерфейс
- [ ] предметы + базовый инвентарь
- [ ] дальние атаки (луки/копья)
- [ ] условие победы
- [ ] уровни + переход между уровнями
